### ISSUE TITLE
track_distance anything "wrong" with using arguement pad = TRUE in geodist::geodist?

### ISSUE THREAD

**Issue by einarhjorleifsson** [AustralianAntarcticDivision/traipse#5]
hi
like this neat package, using the functions on fishing vessel track.
question, not a bug: geodist::geodist takes argument pad = TRUE. any reason why you are not using it in track_distance?
e

**Comment by mdsumner** [comment]
probably not, I just did what I did - I was thinking about the metrics generally, not just distance at the time and (say) the code I use for angles doesn't have padding capability

**Comment by einarhjorleifsson** [comment]
ok. o&o.
